import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage { id, en }

class LanguageProvider extends ChangeNotifier {
  AppLanguage _currentLanguage = AppLanguage.id;

  AppLanguage get currentLanguage => _currentLanguage;

  LanguageProvider() {
    _loadLanguage();
  }

  void _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final langCode = prefs.getString('app_language') ?? 'id';
    _currentLanguage = langCode == 'en' ? AppLanguage.en : AppLanguage.id;
    notifyListeners();
  }

  Future<void> setLanguage(AppLanguage language) async {
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', language == AppLanguage.en ? 'en' : 'id');
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  static const Map<AppLanguage, Map<String, String>> _translations = {
    AppLanguage.id: {
      'login': 'MASUK',
      'username': 'USERNAME',
      'password': 'PASSWORD',
      'enter_username': 'MASUKKAN USERNAME',
      'enter_password': 'MASUKKAN PASSWORD',
      'login_and_setup_pin': 'MASUK DAN SIAPKAN PIN',
      'welcome_back': 'SELAMAT DATANG,',
      'enter_pin_staff': 'SILAKAN MASUKKAN 4 ATAU 6 DIGIT PIN ANDA UNTUK MEMULAI SESI KASIR.',
      'contact_vendor': 'Hubungi Vendor untuk perubahan data',
      'back_to_user_list': 'KEMBALI KE DAFTAR USER',
      'input_pin_security': 'INPUT PIN KEAMANAN',
      'login_as_staff': 'LOGIN SEBAGAI STAFF',
      'choose_your_username': 'PILIH USERNAME ANDA',
      'staff_data_empty': 'DATA STAFF KOSONG',
      'logout_exit': 'LOGOUT / KELUAR',
      'system_status': 'STATUS SISTEM',
      'transaction_status': 'STATUS TRANSAKSI',
      'product_count': 'JUMLAH PRODUK',
      'category_count': 'JUMLAH KATEGORI',
      'table_count': 'JUMLAH MEJA',
      'discount': 'DISKON',
      'has_discount': '(ADA DISKON HARI INI)',
      'no_discount': '(TIDAK ADA DISKON)',
      'not_closed_yet': '* BELUM CLOSING',
      'connecting_to_server': 'MENYAMBUNGKAN KE SERVER...',
      'offline_mode_msg': 'Koneksi internet tidak tersedia. Masuk dalam MODE OFFLINE.',
      'offline_mode_not_ready': 'Sayang sekali mode offline memerlukan data yang sudah disinkron sebelumnya',
      'login_failed': 'Login Gagal. Periksa username dan password Anda.',
      'erp_connection_setup': 'KONEKSI POS DAN ERP SERVER',
      // POS Screen
      'cashier': 'KASIR',
      'search': 'CARI',
      'scan': 'SCAN',
      'hold': 'HOLD',
      'customer': 'PELANGGAN',
      'table': 'MEJA',
      'kitchen': 'DAPUR',
      'subtotal': 'Subtotal',
      'tax': 'Pajak',
      'total': 'TOTAL',
      'number': 'NOMOR',
      'return': 'Kembalian',
      'dine_in': 'DINE IN',
      'take_away': 'TAKE AWAY',
      'online': 'ONLINE',
      'member': 'MEMBER',
      'all_categories': 'SEMUA',
      'empty_cart': 'KERANJANG KOSONG',
      'checkout': 'BAYAR SEKARANG',
      'clear_cart': 'KOSONGI',
      'product_not_found': 'Produk tidak ditemukan',
      'attendance_required': 'ABSENSI WAJIB',
      'clock_in_warning': 'ANDA BELUM MELAKUKAN CLOCK IN! SILAKAN ABSEN TERLEBIH DAHULU.',
      'sync_center': 'SYNC CENTER',
      'settings': 'PENGATURAN',
      'choose_sale_type': 'PILIH TIPE PESANAN',
      'dine_in_desc': 'MAKAN SINI',
      'take_away_desc': 'BUNGKUS',
      'special': 'KHUSUS',
      'others': 'LAINNYA',
      'synchronization': 'SINKRONISASI',
      'system_data': 'DATA & SISTEM',
      'back': 'KEMBALI',
      'sync_products': 'SINKRON PRODUK',
      'product_images': 'GAMBAR PRODUK',
      'sync_topping': 'SINKRON TOPPING',
      'sync_category': 'SINKRON KATEGORI',
      'sync_table': 'DATA MEJA',
      'sync_staff': 'SINKRON STAFF',
      'sync_tax': 'PAJAK & DISKON',
      'sync_payment': 'METODE BAYAR',
      'sync_customer': 'DATA PELANGGAN',
      'sync_business': 'INFO BISNIS / LOGO',
      'posting_sales': 'POSTING SALES',
      'full_sync': 'SINKRON SEMUA (FULL)',
      'printer_setting': 'PENGATURAN PRINTER',
      'invoice_setting': 'FAKTUR / STRUK',
      'discount_approval': 'APPROVAL DISKON',
      'kitchen_printer': 'PRINTER DAPUR (KOT)',
      'menu_management': 'MANAJEMEN MENU',
      'price_config': 'KONFIGURASI HARGA',
      'payment_methods': 'METODE PEMBAYARAN',
      'backup_data': 'BACKUP DATA',
      'restore_data': 'RESTORE DATA',
      'reset_database': 'RESET DATABASE DEVICE',
      'automatic_rounding': 'PEMBULATAN OTOMATIS',
      'calculate_tax': 'HITUNG PAJAK',
      'allow_discount': 'IZINKAN DISKON',
      'duplicate_print': 'CETAK DUPLIKASI (2X)',
      'server_info_location': 'INFORMASI SERVER & LOKASI',
      'business_name': 'NAMA BISNIS',
      'location': 'LOKASI',
      'server_url': 'URL SERVER',
      'product_quick_sync': 'SINKRON PRODUK (CEPAT)',
      'topping_sync': 'SINKRON DATA TOPPING',
      'tax_discount_sync': 'SINKRON DISKON DAN PAJAK',
      'sale_type_sync': 'SINKRON TIPE PESANAN',
      'category_sync': 'SINKRON KATEGORI PRODUK',
      'complementary_data_sync': 'SINKRON DATA PELENGKAP',
      'expense_category_sync': 'SINKRON KATEGORI BIAYA',
      'process_payment': 'PROSES PEMBAYARAN',
      'bill_total': 'TOTAL TAGIHAN',
      'billing_summary': 'RINGKASAN TAGIHAN',
      'payment_security_msg': 'Sistem pembayaran terenkripsi dan aman. Pastikan nominal bayar sudah sesuai.',
      'choose_payment_method': 'PILIH METODE PEMBAYARAN',
      'quick_cash_recommendation': 'REKOMENDASI NOMINAL (UANG CEPAT)',
      'manual_nominal_input': 'INPUT NOMINAL MANUAL',
      'insufficient_nominal': 'NOMINAL BELUM CUKUP',
      'complete_transaction': 'SELESAIKAN TRANSAKSI',
      'total_price': 'TOTAL HARGA',
      'paid_amount': 'DIBAYARKAN',
      'change_amount': 'KEMBALIAN',
      'shortage_amount': 'KEKURANGAN',
      'exact_cash': 'UANG PAS',
      'pos_cashier': 'Kasir',
      'pos_customer_caps': 'PELANGGAN',
      'pos_table_caps': 'MEJA',
      'pos_total_product': 'TOTAL PRODUK',
      'pos_paid': 'Dibayar',
      'pos_change': 'Kembalian',
      'pos_payment_method': 'METODE',
      'pos_printing': 'MENCETAK...',
      'pos_print_receipt_1x': 'CETAK STRUK (1X)',
      'pos_cut_paper': 'Potong Kertas',
      'pos_cut_paper_msg': 'Silakan potong kertas struk pertama, lalu tekan tombol di bawah untuk mencetak salinan (DUPLIKASI).',
      'pos_continue_duplicate': 'LANJUT CETAK DUPLIKASI',
      'pos_print_2x_duplicate': 'CETAK 2X (DUPLIKASI)',
      'pos_no_print': 'TANPA CETAK',
      'pos_close_finish': 'TUTUP / SELESAI',
      'printer_offline': 'PRINTER OFFLINE',
      'report_error': 'ERROR LAPORAN',
      'about_app': 'TENTANG APLIKASI',
      'version_caps': 'VERSI',
      'changelog_caps': 'RIWAYAT PERUBAHAN (CHANGELOG)',
      'reports_closing': 'LAPORAN & CLOSING',
      'shift_summary': 'RINGKASAN SHIFT',
      'daily_z_report': 'Z-REPORT HARIAN',
      'total_transactions': 'TOTAL TRANSAKSI',
      'total_items': 'TOTAL ITEM',
      'omzet_gross': 'OMZET KOTOR',
      'total_net': 'TOTAL BERSIH',
      'print_shift_report': 'CETAK LAPORAN SHIFT',
      'print_z_report': 'CETAK Z-REPORT',
      'daily_closing': 'CLOSING HARIAN',
      'select_date': 'PILIH TANGGAL',
      'no_data_for_date': 'TIDAK ADA DATA UNTUK TANGGAL INI',
      'confirm_closing': 'KONFIRMASI CLOSING',
      'confirm_closing_msg': 'ANDA YAKIN INGIN MELAKUKAN CLOSING DAY?',
      'confirm_closing_ensure': 'PASTIKAN SELURUH HAL BERIKUT TELAH DISELESAIKAN:',
      'cancel': 'BATAL',
      'yes_closing': 'YA, CLOSING',
      'success': 'BERHASIL',
      'closing_success_msg': 'CLOSING DAY TELAH SELESAI DILAKUKAN.',
      'closing_failed': 'CLOSING GAGAL',
    },
    AppLanguage.en: {
      'login': 'LOGIN',
      'username': 'USERNAME',
      'password': 'PASSWORD',
      'enter_username': 'ENTER USERNAME',
      'enter_password': 'ENTER PASSWORD',
      'login_and_setup_pin': 'LOGIN AND SETUP PIN',
      'welcome_back': 'WELCOME BACK,',
      'enter_pin_staff': 'PLEASE ENTER YOUR 4 OR 6 DIGIT PIN TO START CASHIER SESSION.',
      'contact_vendor': 'Contact Vendor for data changes',
      'back_to_user_list': 'BACK TO USER LIST',
      'input_pin_security': 'INPUT SECURITY PIN',
      'login_as_staff': 'LOGIN AS STAFF',
      'choose_your_username': 'CHOOSE YOUR USERNAME',
      'staff_data_empty': 'STAFF DATA EMPTY',
      'logout_exit': 'LOGOUT / EXIT',
      'system_status': 'SYSTEM STATUS',
      'transaction_status': 'TRANSACTION STATUS',
      'product_count': 'PRODUCT COUNT',
      'category_count': 'CATEGORY COUNT',
      'table_count': 'TABLE COUNT',
      'discount': 'DISCOUNT',
      'has_discount': '(DISCOUNT AVAILABLE TODAY)',
      'no_discount': '(NO DISCOUNT)',
      'not_closed_yet': '* NOT CLOSED YET',
      'connecting_to_server': 'CONNECTING TO SERVER...',
      'offline_mode_msg': 'Internet connection unavailable. Entering OFFLINE MODE.',
      'offline_mode_not_ready': 'Unfortunately, offline mode requires previously synced data',
      'login_failed': 'Login Failed. Check your username and password.',
      'erp_connection_setup': 'ERP AND POS CONNECTION',
      // POS Screen
      'cashier': 'CASHIER',
      'search': 'SEARCH',
      'scan': 'SCAN',
      'hold': 'HOLD',
      'customer': 'CUSTOMER',
      'table': 'TABLE',
      'kitchen': 'KITCHEN',
      'subtotal': 'Subtotal',
      'tax': 'Tax',
      'total': 'TOTAL',
      'number': 'NUMBER',
      'return': 'Return',
      'dine_in': 'DINE IN',
      'take_away': 'TAKE AWAY',
      'online': 'ONLINE',
      'member': 'MEMBER',
      'all_categories': 'ALL',
      'empty_cart': 'CART IS EMPTY',
      'checkout': 'PAYMENT',
      'clear_cart': 'CLEAR',
      'product_not_found': 'Product not found',
      'attendance_required': 'ATTENDANCE REQUIRED',
      'clock_in_warning': 'YOU HAVE NOT CLOCKED IN! PLEASE CLOCK IN FIRST.',
      'sync_center': 'SYNC CENTER',
      'settings': 'SETTINGS',
      'choose_sale_type': 'CHOOSE SALE TYPE',
      'dine_in_desc': 'DINE IN',
      'take_away_desc': 'TAKE AWAY',
      'special': 'SPECIAL',
      'others': 'OTHERS',
      'synchronization': 'SYNCHRONIZATION',
      'system_data': 'DATA & SYSTEM',
      'back': 'BACK',
      'sync_products': 'SYNC PRODUCTS',
      'product_images': 'PRODUCT IMAGES',
      'sync_topping': 'SYNC TOPPING',
      'sync_category': 'SYNC CATEGORY',
      'sync_table': 'TABLE DATA',
      'sync_staff': 'SYNC STAFF',
      'sync_tax': 'TAX & DISCOUNT',
      'sync_payment': 'PAYMENT METHODS',
      'sync_customer': 'CUSTOMER DATA',
      'sync_business': 'BUSINESS INFO / LOGO',
      'posting_sales': 'POSTING SALES',
      'full_sync': 'FULL SYNC',
      'printer_setting': 'PRINTER SETTINGS',
      'invoice_setting': 'INVOICE / RECEIPT',
      'discount_approval': 'DISCOUNT APPROVAL',
      'kitchen_printer': 'KITCHEN PRINTER (KOT)',
      'menu_management': 'MENU MANAGEMENT',
      'price_config': 'PRICE CONFIGURATION',
      'payment_methods': 'PAYMENT METHODS',
      'backup_data': 'BACKUP DATA',
      'restore_data': 'RESTORE DATA',
      'reset_database': 'RESET DEVICE DATABASE',
      'automatic_rounding': 'AUTOMATIC ROUNDING',
      'calculate_tax': 'CALCULATE TAX',
      'allow_discount': 'ALLOW DISCOUNT',
      'duplicate_print': 'DUPLICATE PRINT (2X)',
      'server_info_location': 'SERVER INFO & LOCATION',
      'business_name': 'BUSINESS NAME',
      'location': 'LOCATION',
      'server_url': 'SERVER URL',
      'product_quick_sync': 'SYNC PRODUCTS (FAST)',
      'topping_sync': 'SYNC TOPPING DATA',
      'tax_discount_sync': 'SYNC DISCOUNT AND TAX',
      'sale_type_sync': 'SYNC SALE TYPES',
      'category_sync': 'SYNC PRODUCT CATEGORIES',
      'complementary_data_sync': 'SYNC COMPLEMENTARY DATA',
      'expense_category_sync': 'SYNC EXPENSE CATEGORIES',
      'process_payment': 'PROCESS PAYMENT',
      'bill_total': 'BILL TOTAL',
      'billing_summary': 'BILLING SUMMARY',
      'payment_security_msg': 'Payment system is encrypted and secure. Please ensure the payment amount is correct.',
      'choose_payment_method': 'CHOOSE PAYMENT METHOD',
      'quick_cash_recommendation': 'QUICK CASH RECOMMENDATION',
      'manual_nominal_input': 'MANUAL NOMINAL INPUT',
      'insufficient_nominal': 'INSUFFICIENT NOMINAL',
      'complete_transaction': 'COMPLETE TRANSACTION',
      'total_price': 'TOTAL PRICE',
      'paid_amount': 'PAID AMOUNT',
      'change_amount': 'CHANGE',
      'shortage_amount': 'SHORTAGE',
      'exact_cash': 'EXACT CASH',
      'pos_cashier': 'Cashier',
      'pos_customer_caps': 'CUSTOMER',
      'pos_table_caps': 'TABLE',
      'pos_total_product': 'TOTAL PRODUCTS',
      'pos_paid': 'Paid',
      'pos_change': 'Change',
      'pos_payment_method': 'METHOD',
      'pos_printing': 'PRINTING...',
      'pos_print_receipt_1x': 'PRINT RECEIPT (1X)',
      'pos_cut_paper': 'Cut Paper',
      'pos_cut_paper_msg': 'Please cut the first receipt, then press the button below to print the duplicate.',
      'pos_continue_duplicate': 'CONTINUE DUPLICATE PRINT',
      'pos_print_2x_duplicate': 'PRINT 2X (DUPLICATE)',
      'pos_no_print': 'NO PRINT',
      'pos_close_finish': 'CLOSE / FINISH',
      'printer_offline': 'PRINTER OFFLINE',
      'report_error': 'REPORT ERROR',
      'about_app': 'ABOUT APPLICATION',
      'version_caps': 'VERSION',
      'changelog_caps': 'CHANGELOG HISTORY',
      'reports_closing': 'REPORTS & CLOSING',
      'shift_summary': 'SHIFT SUMMARY',
      'daily_z_report': 'DAILY Z-REPORT',
      'total_transactions': 'TOTAL TRANSACTIONS',
      'total_items': 'TOTAL ITEMS',
      'omzet_gross': 'GROSS REVENUE',
      'total_net': 'TOTAL NET',
      'print_shift_report': 'PRINT SHIFT REPORT',
      'print_z_report': 'PRINT Z-REPORT',
      'daily_closing': 'DAILY CLOSING',
      'select_date': 'SELECT DATE',
      'no_data_for_date': 'NO DATA FOR THIS DATE',
      'confirm_closing': 'CONFIRM CLOSING',
      'confirm_closing_msg': 'ARE YOU SURE YOU WANT TO RUN DAILY CLOSING?',
      'confirm_closing_ensure': 'ENSURE ALL OF THE FOLLOWING ARE COMPLETED:',
      'cancel': 'CANCEL',
      'yes_closing': 'YES, CLOSING',
      'success': 'SUCCESS',
      'closing_success_msg': 'DAILY CLOSING HAS BEEN COMPLETED SUCCESSFULLY.',
      'closing_failed': 'CLOSING FAILED',
    }
  };
}
